clusters:
  - name: "rome"
    runtime: "kind"
    cni: "kindnet"
    nodes: 2
  - name: "milan"
    runtime: "kind"
    cni: "kindnet"
    nodes: 2

tools:
  liqo:
    installations:
      - cluster: "rome"
      - cluster: "milan"
    peerings:
      - ["rome", "milan"]
